# For pp.py.
R_MULT = int(1e6)

# For libe.py.
K_TO_TAU_RATIO = 6.

NUM_K2_1D = 6
NUM_K2_1D_64L = 12
NUM_K2_2D = 4

XI_NUM_FITTED_PARAMS = 2

XI_ERR_MULT = 1.0    #ADJUST FOR OVERLY OPTIMISTIC ERROR BARS DUE TO
                     #CORRELATIONS AMOUNG THE ERROR BARS ON THE Gt(k).
#XI_ERR_O_XI_MAX = 0.4

